--require('at.libs')

require('at.plugins')
require('at.settings')
require('at.colors')
-- require('at.statusline')
require('at.mappings')
require('at.plugins.config')
require('at.telescope')
require('at.lsp')
