-- require('at.libs')

require('at.settings')
require('at.plugins')
require('at.plugins.user')
require('at.plugins.config')
require('at.colors')
require('at.mappings')
require('at.telescope')
require('at.lsp')
require('at.status-line')
require('at.git')
require('at.completion')
